### ISSUE TITLE
Uncontrolled precision error

### ISSUE THREAD

**Issue by Mannyari** [lightning-auriga/interpolate-genetic-position#20]
Hi,

I encountered an error while running the interpolate-genetic-position tool with the following command:

interpolate-genetic-position.out -i ANT1_ANNOVAR.bim -p bim -g /dati/archivio_ricerca/NEUROSCIENZE_SILANI/Mega2/v6.0.0/BOLT-LMM_v2.4.1/tables/genetic_map_hg38_withX.txt.gz -m bolt --precision 25600 --fixed-output-width 6000 -o ANT1_ANNOVAR_pos.bim -f bim

As you can see, despite setting high values for --precision (25600) and --fixed-output-width (6000), I continue to receive the following error:

what(): write: an output genetic position is smaller than the position of a previous output for the same chromosome. This is probably caused by uncontrolled precision errors, either in one of the inputs or in the logic of this program. The most likely way to solve this error is to try increasing --precision and --fixed-output-width in combination until sufficient precision is preserved for the results to remain internally consistent.
Aborted (core dumped)

What would you suggest?

Many thanks,
Arianna

**Comment by Mannyari** [comment]
HI Light,

Thanks a lot for the quick reply! I tried loading the dataset into plink
and writing it back out again, but I'm still getting the same error. You
can find enclosed the binary files I'm using, if you might have the chance
to take a look. Thanks a lot!

Best,
Arianna
 ANT1_ANNOVAR.bed
<https://drive.google.com/file/d/1CAxDduue_TztGg3pDs1wz4pXFAeX7fg-/view?usp=drive_web>
 ANT1_ANNOVAR.bim
<https://drive.google.com/file/d/17PNTB9y4YbIZZAIMkkfaPkJgJLr8KDmd/view?usp=drive_web>
 ANT1_ANNOVAR.fam
<https://drive.google.com/file/d/1-eSfCgePC7n4sYoyAyB8ZjNCIZ5Zs0o3/view?usp=drive_web>

Il giorno gio 19 dic 2024 alle ore 16:15 Lightning Auriga <
***@***.***> ha scritto:

**Comment by lightning-auriga** [comment]
Hi, thanks so much for posting these. It does indeed look like a bug in how the software is interpreting bolt-style map files. I'll attempt to patch and add appropriate tests today (it's early morning where I am).

**Comment by lightning-auriga** [comment]
Hi again @Mannyari 

Thanks again for reporting this. I've hotfixed to 1.2.2 and posted the build in my conda channel. In short, it seems that bolt's annotation files are somewhat inconsistent in how they report cM/Mb rate, and bolt itself ignores the rate column entirely and replaces it with an _ad hoc_ calculation of the effective rate based on elapsed physical and genetic position. I've modified the bolt loading logic to do the same recalculation as bolt does. It seems to only affect some of bolt's rate files in some places, which is thoroughly unnerving.

In any case, I installed the 1.2.2 version with conda and ran it on your example data and it runs to completion without issue. The precision argument is not required; I'd probably recommend still using the fixed-output-width setting to something you find suitable, as the changes in gpos are so small that the truncated output makes it look like nothing is happening between certain positions.

Please let me know if this doesn't solve your issue or if you run into further difficulties. Thank you very much for helping me improve this program.

**Comment by Mannyari** [comment]
Hi Light,

This worked perfectly! Thanks a lot.
Arianna

Il giorno ven 20 dic 2024 alle ore 17:53 Lightning Auriga <
***@***.***> ha scritto:

**Comment by lightning-auriga** [comment]
I'm delighted to hear it.
